name: auto_update
description: This plugin for Flutter handles a native app update without an official application store.
version: 0.0.3
homepage: https://github.com/ehoraizon/auto_update

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^1.1.2
  flutter:
    sdk: flutter
  win32: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.egarcia.auto_update
        pluginClass: AutoUpdatePlugin
      windows:
        pluginClass: AutoUpdatePlugin

